name: Continuous Delivery
on: 
  push:
    branches:
      - main

jobs:
  Deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: simulating cintinuous delivery 
        uses: actions/upload-artifact@v7
        with:
          name: my-artifact-zipped.zip
          path: |
            '**.py'
            README.md